packages:
  - ./apps/*
  - ./packages/*
onlyBuiltDependencies:
  - bun
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  "@parcel/watcher": false
  bun: set this to true or false
  esbuild: false
  msgpackr-extract: false
  msw: false
  sharp: false
