// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/collection/:name": {
    params: {
      "name": string;
    };
  };
  "/collection/:name/:id": {
    params: {
      "name": string;
      "id": string;
    };
  };
  "/api/ai/command": {
    params: {};
  };
  "/api/ai/copilot": {
    params: {};
  };
  "/api/uploadthing": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/collection/:name" | "/collection/:name/:id" | "/api/ai/command" | "/api/ai/copilot" | "/api/uploadthing";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/collection/:name" | "/collection/:name/:id" | "/api/ai/command" | "/api/ai/copilot" | "/api/uploadthing";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/collection/page.tsx": {
    id: "routes/collection/page";
    page: "/collection/:name";
  };
  "routes/collection/document/page.tsx": {
    id: "routes/collection/document/page";
    page: "/collection/:name/:id";
  };
  "routes/api/ai/command/route.ts": {
    id: "routes/api/ai/command/route";
    page: "/api/ai/command";
  };
  "routes/api/ai/copilot/route.ts": {
    id: "routes/api/ai/copilot/route";
    page: "/api/ai/copilot";
  };
  "routes/api/uploadthing/route.ts": {
    id: "routes/api/uploadthing/route";
    page: "/api/uploadthing";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/layout": typeof import("./src/routes/layout.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
  "routes/collection/page": typeof import("./src/routes/collection/page.tsx");
  "routes/collection/document/page": typeof import("./src/routes/collection/document/page.tsx");
  "routes/api/ai/command/route": typeof import("./src/routes/api/ai/command/route.ts");
  "routes/api/ai/copilot/route": typeof import("./src/routes/api/ai/copilot/route.ts");
  "routes/api/uploadthing/route": typeof import("./src/routes/api/uploadthing/route.ts");
};